In [9]:
import numpy as np
arr=np.array([1,2,3,4,5,6])
x=arr.copy()
arr[0]=42
print(arr) 
print(x)



import numpy as np
arr=np.array([1,2,3,4,5])
x=arr.copy()
arr[0]=21
print(arr)
print(x)


import numpy as np
arr=np.array([1,2,3,4,5])
x=arr.view()
arr[0]=21
print(arr)
print(x)

import numpy as np
arr=np.array([
             


[42  2  3  4  5  6]
[1 2 3 4 5 6]
[21  2  3  4  5]
[1 2 3 4 5]
[21  2  3  4  5]
[21  2  3  4  5]
