In [3]:
# NUMPY DOT FUNCTION
# ---------------------------

import numpy as np
array1=np.array([1,3,5])
array2=np.array([2,4,6])
result=np.dot(array1,array2)
print(result)

44


In [7]:
import numpy as np
array1=np.array([4,5,89,45,69])
array2=np.array([5,8,69,25,74])
anila=np.dot(array1,array2)
(anila)

12432

In [21]:
# NUMPY INNER FUNCTION
# --------------------------

import numpy as np
array1=np.array([[1,3],
                 [5,7]])
array2=np.array([[2,4],
                 [6,8]])
anila=np.inner(array1,array2)
(anila)   

                 


                

array([[14, 30],
       [38, 86]])

In [25]:
# NUMPY OUTER FUNCTION
# ------------------------

import numpy as np
array1=np.array([1,3,5])
array2=np.array([2,4,6])
anila=np.outer(array1,array2)
(anila)

array([[ 2,  4,  6],
       [ 6, 12, 18],
       [10, 20, 30]])

In [31]:
# NUMPY DET FUNCTION
# ---------------------

import numpy as np
array1=np.array([[2,5],
                 [6,8]])
anila=np.linalg.det(array1)
anila
                

-14.000000000000004

In [35]:
# NUMPY SOLVE FUNCTION
# -----------------------

import numpy as np
noni =np.array([[5,8],
                [3,7]])
nithi =np.array([8,4])
revu =np.linalg.solve(noni,nithi)
revu

array([ 2.18181818, -0.36363636])

In [39]:
# NUMPY INVERSE FUNCTION
# ---------------------------

import numpy as np
array1=np.array([[5,9],
                 [7,2]])
anila=np.linalg.inv(array1)
anila
                

array([[-0.03773585,  0.16981132],
       [ 0.13207547, -0.09433962]])