In [1]:
!pip install numpy

In [3]:
import numpy as np

arr1 = np.array([1, 2, 3, 4, 5])

print(arr1)

[1 2 3 4 5]


In [5]:
import numpy as np

print(np.__version__)

1.26.4


In [9]:
import numpy as np

arr2 = np.array([122, 2, 377, 4, 3335])

arr2

array([ 122,    2,  377,    4, 3335])

In [11]:
#0Dimention
import numpy as np

arr = np.array(12)

print(arr)

12


In [21]:
#2D
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr)
print(arr.ndim)

[[1 2 3]
 [4 5 6]]
2


In [19]:
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(arr)
print(arr.ndim)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
3
